# Generated by Django 4.0.6 on 2022-07-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planID', models.TextField(unique=True)),
                ('userID', models.TextField()),
                ('selectedAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selectedTenure', models.IntegerField()),
                ('startedDate', models.DateField(auto_now=True)),
                ('depositedAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefitPercentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benefitType', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
