# Generated by Django 4.0.6 on 2022-07-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_alter_plan_promotionenddate_and_more'),
        ('customerGoals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customergoals',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customergoals',
            name='userID',
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='benefitType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='planID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
        ),
    ]
