# Generated by Django 4.0.6 on 2022-07-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planID', models.TextField(unique=True)),
                ('planName', models.TextField()),
                ('amountOptions', models.TextField()),
                ('tenureOptions', models.TextField()),
                ('benefitPercentage', models.TextField()),
                ('benefitType', models.TextField()),
                ('promotion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
