# Generated by Django 4.0.6 on 2022-07-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_amount_tenure_remove_plan_planid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='promotionEndDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='promotionStartDate',
            field=models.DateField(blank=True),
        ),
    ]
