# Generated by Django 4.0.6 on 2022-07-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_plan_promotionenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='promotionEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='promotionStartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
